version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
  serverless: circleci/serverless-framework@1.0.1
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: build
          command: yarn build
  deploy:
    executor: serverless/default
    steps:
      - aws-cli/setup
      - serverless/setup:
          app-name: serverless-framework-orb
          org-name: circleci
      - run:
          name: deploy
          command: client deploy --no-confirm
workflows:
  deploy:
    jobs:
      - build
      - deploy
      